### ISSUE TITLE
Login Auth error , status:401

### ISSUE THREAD

**Issue by rayamoh** [proxoar/talk#125]
Container starts fine. http://localhost:8000 is showing home page /auth endpoint. Giving below error in the log. It is not clear what is causing this error. Executed container with LOG_LEVEL=debug , does not give details. Please assist troubleshooting the issue

`2024-02-03 13:35:01 1.7069853014169762e+09      WARN    echozap@v1.1.3/logger.go:47     Client error    {"remote_ip": "172.17.0.1", "latency": "141.202µs", "host": "localhost:8000", "request": "GET /api/health", "status": 401, "size": 45, "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36", "request_id": ""}`

**Comment by proxfly** [comment]
Typically, this occurs for two main reasons:

1. On initial launch, the web page (login page) issues a `GET /api/health` request to determine whether a password is necessary. If not, it proceeds to the chat page; otherwise(401), it remains on the login page, waiting for the user to enter a password.

2. The login page has received an invalid password entry.

If you’re on the chat page, ignore this error. Otherwise, ensure you’ve entered the correct password.

You can find the passwords in the `talk.yaml` file:
```
server:
  passwords:
    - "pass01"
    - "pass01"
```

**Comment by rayamoh** [comment]
Thank you so much. Login text box was not visible , so did not know have to enter password

**Comment by proxfly** [comment]
<img width="876" alt="image" src="https://github.com/proxoar/talk/assets/27894831/843ac842-b424-49d3-a5f5-6571dacc2f84">
To embrace minimalism, I’ve removed the text box’s caret and border. Apologies for any misunderstanding🤣.
